title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://Helmsman-Lab.github.io/cs324_LLM

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Helmsman-Lab/cs324_LLM
